<div class="block_social block">
    <img class="img-responsive" src="https://images.unsplash.com/photo-1445964047600-cdbdb873673d?crop=entropy&fit=crop&fm=jpg&h=775&ixjsv=2.1.0&ixlib=rb-0.3.5&q=80&w=1600">
    <img class="img-circle center-block" width="75" style="margin-top:-35px;border:3px solid white;" src="<?php echo $user_image_url; ?>">
    <p class="text-center text-bold"><?php echo $USER->firstname; ?> <?php echo $USER->lastname; ?></p>
    <div class="content">
    </div>
</div>
